In [1]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install pyreadstat

Looking in indexes: https://nexus.beta.innovation.insee.eu/repository/pypi-public/simple
Requirement already satisfied: pyreadstat in /opt/conda/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: pandas>0.24.0 in /opt/conda/lib/python3.7/site-packages (from pyreadstat) (0.25.3)
Requirement already satisfied: numpy>=1.13.3 in /opt/conda/lib/python3.7/site-packages (from pandas>0.24.0->pyreadstat) (1.17.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/conda/lib/python3.7/site-packages (from pandas>0.24.0->pyreadstat) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.7/site-packages (from pandas>0.24.0->pyreadstat) (2019.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>0.24.0->pyreadstat) (1.13.0)

In [2]:
import os
import s3fs
import pandas as pd
import numpy as np

In [3]:
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': 'http://minio.stable.innovation.insee.eu'})

In [4]:
remote_data_dir="s3://groupe-1033/data"

In [5]:
fs.ls(remote_data_dir)

['groupe-1033/data/476-E220-2015_Archivage (liste variables).doc',
 'groupe-1033/data/DictionnaireRP.ods',
 'groupe-1033/data/DictionnaireSirus.odt',
 'groupe-1033/data/DonneesTransmisesHackathon.zip',
 'groupe-1033/data/GENETAB18.csv',
 'groupe-1033/data/RP',
 'groupe-1033/data/SIRUS.csv',
 'groupe-1033/data/SIRUS_VINCENT.csv',
 'groupe-1033/data/Sirus']

## Data/sirus.csv

In [5]:
fs.info(os.path.join(remote_data_dir,'SIRUS.csv'))

{'Key': 'groupe-1033/data/SIRUS.csv',
 'LastModified': datetime.datetime(2019, 12, 10, 16, 57, 12, 712000, tzinfo=tzlocal()),
 'ETag': '"68efc224a15c290b16d1a7ca03417578-222"',
 'Size': 1165069155,
 'StorageClass': 'STANDARD',
 'Owner': {'DisplayName': '', 'ID': ''},
 'type': 'file',
 'size': 1165069155,
 'name': 'groupe-1033/data/SIRUS.csv'}

In [6]:
with fs.open(os.path.join(remote_data_dir,'SIRUS.csv')) as f:
    df = pd.read_csv(f, sep=";")
print('nb lines : {}'.format(len(df)))
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

nb lines : 8264324

,Unnamed: 0,sirus_id,adr_depcom,adr_l6,pour_recherche,codage_vincent,libelle_vincent,qualite
0,0,325175,13204,13004 MARSEILLE 4,13004 MARSEILLE 4;MARSEILLE 4E ARRONDISSEMENT;...,13204,MARSEILLE 4E ARRONDISSEMENT,appariement
1,1,5420021,80001,80100 ABBEVILLE,80100 ABBEVILLE;ABBEVILLE;80;49.93426970808182...,80001,ABBEVILLE,appariement
2,2,5420120,62550,62140 MARCONNELLE,62140 MARCONNELLE;MARCONNELLE;62;50.4606504068...,62550,MARCONNELLE,appariement
3,3,5440110,04070,04000 DIGNE-LES-BAINS,04000 DIGNE-LES-BAINS;DIGNE LES BAINS;04;44.07...,04070,DIGNE LES BAINS,appariement
4,4,5440565,04209,04200 SISTERON,"04200 SISTERON;SISTERON;04;44.07562820034571,6...",04209,SISTERON,appariement

In [18]:
df.columns

Index(['Unnamed: 0', 'sirus_id', 'adr_depcom', 'adr_l6', 'pour_recherche',
       'codage_vincent', 'libelle_vincent', 'qualite'],
      dtype='object')

In [44]:
df[df['adr_depcom'] != df['codage_vincent']][df['codage_vincent'] != 'xxxxx']

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,Unnamed: 0,sirus_id,adr_depcom,adr_l6,pour_recherche,codage_vincent,libelle_vincent,qualite
1430,1430,12863650,50602,50110 CHERBOURG-EN-COTENTIN,50110 CHERBOURG-EN-COTENTIN;CHERBOURG EN COTEN...,50129,CHERBOURG EN COTENTIN,appariement
1450,1450,12871265,50602,50110 CHERBOURG-EN-COTENTIN,50110 CHERBOURG-EN-COTENTIN;CHERBOURG EN COTEN...,50129,CHERBOURG EN COTENTIN,appariement
1455,1455,12871315,50173,50120 CHERBOURG-EN-COTENTIN,50120 CHERBOURG-EN-COTENTIN;CHERBOURG EN COTEN...,50129,CHERBOURG EN COTENTIN,appariement
1493,1493,12888830,50173,50120 CHERBOURG-EN-COTENTIN,50120 CHERBOURG-EN-COTENTIN;CHERBOURG EN COTEN...,50129,CHERBOURG EN COTENTIN,appariement
1747,1748,13245998,49346,49350 GENNES-VAL-DE-LOIRE,49350 GENNES-VAL-DE-LOIRE;GENNES VAL DE LOIRE;...,49261,GENNES VAL DE LOIRE,appariement
...,...,...,...,...,...,...,...,...
8131874,8135158,998269211,92026,92096 PARIS LA DEFENSE CEDEX,92096 PARIS LA DEFENSE CEDEX;PARIS LA DEFENSE;...,92LDF,PARIS LA DEFENSE,appariement
8131875,8135159,998269518,75116,75116 PARIS,"75116 PARIS;PARIS;75;48.85241562520098,2.36265...",75056,PARIS,appariement
8131879,8135163,998289508,75116,75016 PARIS,"75016 PARIS;PARIS;75;48.85241562520098,2.36265...",75056,PARIS,appariement
8131936,8135220,998551113,2A118,20143 FOZZANO,"20143 FOZZANO;FOZZANO;20;42.25110968731284,9.1...",20118,FOZZANO,appariement
8131965,8135249,998660708,92026,92932 PARIS LA DEFENSE CEDEX,92932 PARIS LA DEFENSE CEDEX;PARIS LA DEFENSE;...,92LDF,PARIS LA DEFENSE,appariement

In [45]:
set(df['qualite'].values)

{'appariement', 'impossible', 'pas_ok'}

## Data/SIRUS_VINCENT.csv

In [5]:
with fs.open(os.path.join(remote_data_dir,'SIRUS_VINCENT.csv')) as f:
    df_sirusV = pd.read_csv(f, sep=";")
print('nb lines : {}'.format(len(df_sirusV)))
df_sirusV.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (1,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

nb lines : 8264324

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
0,0,325175,13204,13004 MARSEILLE 4;MARSEILLE 4E ARRONDISSEMENT;...,13204,MARSEILLE 4E ARRONDISSEMENT,appariement,NaN,13204,13204,1
1,1,5420021,80001,80100 ABBEVILLE;ABBEVILLE;80;49.93426970808182...,80001,ABBEVILLE,appariement,NaN,80001,80001,1
2,2,5420120,62550,62140 MARCONNELLE;MARCONNELLE;62;50.4606504068...,62550,MARCONNELLE,appariement,NaN,62550,62550,1
3,3,5440110,04070,04000 DIGNE-LES-BAINS;DIGNE LES BAINS;04;44.07...,04070,DIGNE LES BAINS,appariement,NaN,04070,04070,1
4,4,5440565,04209,"04200 SISTERON;SISTERON;04;44.07562820034571,6...",04209,SISTERON,appariement,NaN,04209,04209,1

In [11]:
df_sirusV['codage_v_bis'][df_sirusV['codage_v_bis'].notna()]

1426172    02735;Tannières
Name: codage_v_bis, dtype: object

In [13]:
df_sirusV.iloc[1426172]

Unnamed: 0                                                     1426172
sirus_id                                                     402777643
adr_depcom                                                       67124
pour_recherche       67836 TANNERIES CEDEX;TANNERIES;67;48.68660799...
codage_v                                                         67169
libelle_v                                                        Gries
qualite                                                              4
codage_v_bis                                           02735;Tannières
adr_depcom_actuel                                                67124
codage_v_actuel                                                  67169
comparaison                                                          0
Name: 1426172, dtype: object

In [15]:
set(df_sirusV['qualite'].values)

{'1', '2', '3', '4', 'appariement', 'impossible'}

In [21]:
df_sirusV[df_sirusV['adr_depcom'] != df_sirusV['adr_depcom_actuel']]

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
58923,58923,130016447,74181,74370 EPAGNY METZ-TESSY;EPAGNY METZ TESSY;74;4...,74112,EPAGNY METZ TESSY,appariement,NaN,74112,74112,1
62713,62713,191411123,14697,14170 SAINT-PIERRE-EN-AUGE;SAINT PIERRE EN AUG...,14654,SAINT PIERRE EN AUGE,appariement,NaN,14654,14654,1
63466,63466,192710168,27293,27240 MESNILS-SUR-ITON;MESNILS SUR ITON;27;49....,27198,MESNILS SUR ITON,appariement,NaN,27198,27198,1
71594,71594,200033991,79211,"79110 PIOUSSAY;PIOUSSAY;79;46.5264361671283,-0...",79211,PIOUSSAY,appariement,NaN,79140,79140,1
76701,76701,210500435,05043,05500 AUBESSAGNE;AUBESSAGNE;05;44.574125698114...,05039,AUBESSAGNE,appariement,NaN,05039,05039,1
...,...,...,...,...,...,...,...,...,...,...,...
8250191,8250191,P18063575,74181,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,74112,xxxxx,-1
8252864,8252864,P18093807,14185,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,14514,xxxxx,-1
8256269,8256269,P18097333,74181,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,74112,xxxxx,-1
8260814,8260814,P18101985,44160,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44003,xxxxx,-1
8264129,8264129,P18105364,44160,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44003,xxxxx,-1

In [18]:
df_sirusV[df_sirusV['adr_depcom'] != df_sirusV['adr_depcom_actuel']][df_sirusV['adr_depcom_actuel'] != df_sirusV['codage_v']]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
71594,71594,200033991,79211,"79110 PIOUSSAY;PIOUSSAY;79;46.5264361671283,-0...",79211,PIOUSSAY,appariement,NaN,79140,79140,1
77231,77231,210702528,07252,07310 SAINT JULIEN BOUTIERES;SAINT JULIEN BOUT...,07252,SAINT JULIEN BOUTIERES,appariement,NaN,07103,07103,1
79485,79485,211401856,14185,14130 COUDRAY RABUT;COUDRAY RABUT;14;49.116676...,14185,COUDRAY RABUT,appariement,NaN,14514,14514,1
79574,79574,211403076,14307,14210 GOUPILLIERES;GOUPILLIERES;14;49.11667660...,14307,GOUPILLIERES,appariement,NaN,14713,14713,1
79757,79757,211406046,14604,14340 SAINT LAURENT DU MONT;SAINT LAURENT DU M...,14604,SAINT LAURENT DU MONT,appariement,NaN,14126,14126,1
...,...,...,...,...,...,...,...,...,...,...,...
8250191,8250191,P18063575,74181,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,74112,xxxxx,-1
8252864,8252864,P18093807,14185,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,14514,xxxxx,-1
8256269,8256269,P18097333,74181,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,74112,xxxxx,-1
8260814,8260814,P18101985,44160,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44003,xxxxx,-1
8264129,8264129,P18105364,44160,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44003,xxxxx,-1

In [22]:
df_sirusV[df_sirusV['codage_v_actuel'] != df_sirusV['codage_v']]

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
5236,5236,20760187,2A004,"20090 AJACCIO;AJACCIO;20;42.25110968731284,9.1...",20004,AJACCIO,appariement,NaN,2A004,2A004,1
5238,5238,20789780,2B033,"20600 BASTIA;BASTIA;20;42.25110968731284,9.163...",20033,BASTIA,appariement,NaN,2B033,2B033,1
5239,5239,20790648,2A004,"20000 AJACCIO;AJACCIO;20;42.25110968731284,9.1...",20004,AJACCIO,appariement,NaN,2A004,2A004,1
5240,5240,20800405,2A004,"20090 AJACCIO;AJACCIO;20;42.25110968731284,9.1...",20004,AJACCIO,appariement,NaN,2A004,2A004,1
5241,5241,20800439,2A004,"20000 AJACCIO;AJACCIO;20;42.25110968731284,9.1...",20004,AJACCIO,appariement,NaN,2A004,2A004,1
...,...,...,...,...,...,...,...,...,...,...,...
8131831,8131831,998036313,2A008,20700 AJACCIO CEDEX 9;AJACCIO;20;42.2511096873...,20004,AJACCIO,appariement,NaN,2A008,2A004,0
8131832,8131832,998036511,2A247,20137 PORTO VECCHIO;PORTO VECCHIO;20;42.251109...,20247,PORTO VECCHIO,appariement,NaN,2A247,2A247,1
8131833,8131833,998036610,2A247,20137 PORTO VECCHIO;PORTO VECCHIO;20;42.251109...,20247,PORTO VECCHIO,appariement,NaN,2A247,2A247,1
8131834,8131834,998036719,2A249,20110 PROPRIANO;PROPRIANO;20;42.25110968731284...,20249,PROPRIANO,appariement,NaN,2A249,2A249,1
8131936,8131936,998551113,2A118,"20143 FOZZANO;FOZZANO;20;42.25110968731284,9.1...",20118,FOZZANO,appariement,NaN,2A118,2A118,1

In [23]:
df_sirusV[df_sirusV['codage_v_actuel'] != df_sirusV['codage_v']][df_sirusV['codage_v_actuel'] != df_sirusV['adr_depcom_actuel']]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
81831,81831,212003271,2B327,20248 MACINAGGIO;MACINAGGIO;20;42.251109687312...,20256,Rapaggio,4,NaN,2B327,2B256,0
104646,104646,217605781,76578,76440 SAINTE GENEVIEVE;SAINTE GENEVIEVE;76;49....,76579,SAINTE GENEVIEVE,appariement,NaN,76578,76063,0
112645,112645,252000682,2B327,20248 MACINAGGIO;MACINAGGIO;20;42.251109687312...,20256,Rapaggio,4,NaN,2B327,2B256,0
132698,132698,300586724,2A271,20700 AJACCIO CEDEX 9;AJACCIO;20;42.2511096873...,20004,AJACCIO,appariement,NaN,2A271,2A004,0
448889,448889,330268897,2B313,"20200 BASTIA;BASTIA;20;42.25110968731284,9.163...",20033,BASTIA,appariement,NaN,2B313,2B033,0
...,...,...,...,...,...,...,...,...,...,...,...
7796602,7796602,840952089,2B327,20248 MACINAGGIO;MACINAGGIO;20;42.251109687312...,20256,Rapaggio,4,NaN,2B327,2B256,0
7819438,7819438,841252281,76578,76440 SAINTE GENEVIEVE;SAINTE GENEVIEVE;76;49....,76579,SAINTE GENEVIEVE,appariement,NaN,76578,76063,0
7841073,7841073,841534282,76578,76440 SAINTE GENEVIEVE;SAINTE GENEVIEVE;76;49....,76579,SAINTE GENEVIEVE,appariement,NaN,76578,76063,0
7913869,7913869,842470452,2A004,"20150 OTA;OTA;20;42.25110968731284,9.163645357...",20198,OTA,appariement,NaN,2A004,2A198,0
8131831,8131831,998036313,2A008,20700 AJACCIO CEDEX 9;AJACCIO;20;42.2511096873...,20004,AJACCIO,appariement,NaN,2A008,2A004,0

In [24]:
set(df_sirusV['comparaison'].values)

{-1, 0, 1}

In [7]:
comp_1 = df_sirusV[df_sirusV['comparaison'] == 1]
comp_1[comp_1['codage_v_actuel'] != comp_1['adr_depcom_actuel']]

Empty DataFrame
Columns: [Unnamed: 0, sirus_id, adr_depcom, pour_recherche, codage_v, libelle_v, qualite, codage_v_bis, adr_depcom_actuel, codage_v_actuel, comparaison]
Index: []

In [8]:
comp_minus1 = df_sirusV[df_sirusV['comparaison'] == -1]
comp_minus1[comp_minus1['codage_v_actuel']]

,Unnamed: 0,sirus_id,adr_depcom,pour_recherche,codage_v,libelle_v,qualite,codage_v_bis,adr_depcom_actuel,codage_v_actuel,comparaison
16,16,5520325,75118,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,75118,xxxxx,-1
24,24,5580113,44210,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44210,xxxxx,-1
46,46,5720362,30326,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,30326,xxxxx,-1
62,62,5775556,44184,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44184,xxxxx,-1
106,106,6002448,44132,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,44132,xxxxx,-1
...,...,...,...,...,...,...,...,...,...,...,...
8264319,8264319,P18105558,32256,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,32256,xxxxx,-1
8264320,8264320,P18105559,86194,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,86194,xxxxx,-1
8264321,8264321,P18105560,85047,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,85047,xxxxx,-1
8264322,8264322,P18105561,33281,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,33281,xxxxx,-1
8264323,8264323,P18105562,75116,";;;48.857426,2.351965",xxxxx,xxxxx,impossible,NaN,75116,xxxxx,-1

## data/Sirus/split/sirus18_01.csv

In [7]:
with fs.open(os.path.join(remote_data_dir,'Sirus/split/sirus18_01.csv')) as f:
    df_sirus18 = pd.read_csv(f, sep=";")
print('nb lines : {}'.format(len(df_sirus18)))
df_sirus18.head()

nb lines : 73723

,sirus_id,nic,ape,apet,eff_3112_et,eff_etp_et,eff_et_effet_daaaammjj,enseigne_et1,nom_comm_et,adr_et_loc_geo,...,region_mult,tr_eff_etp,cj,denom,denom_condense,sigle,enseigne,eff_3112_uniteLegale,eff_etp_uniteLegale,eff_effet_daaaammjj_uniteLegale
0,37241031,30,7022Z,7022Z,NaN,NaN,NaN,NaN,NaN,1435,...,MULT,NN,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40471971,16,8110Z,8110Z,0.0,0.0,20151231.0,NaN,NaN,105300657,...,MONO,00,9110,IMMEUBLE LE VENISE,IMMEUBLE LE VENISE,NaN,NaN,0.0,0.0,20151231.0
2,40472151,14,8110Z,8110Z,0.0,0.0,20081231.0,NaN,NaN,103300249,...,MONO,00,9110,COPR LES JONQUILLES,COPR LES JONQUILLES,NaN,NaN,0.0,0.0,20081231.0
3,40472250,14,8110Z,8110Z,3.0,1.0,20171231.0,NaN,NaN,116000083,...,MONO,01,9110,COPR RESIDENCE VOLTAIRE,COPR RESIDENCE VOLTAIRE,NaN,NaN,3.0,1.0,20171231.0
4,40472920,12,8110Z,8110Z,1.0,1.0,20161231.0,NaN,NaN,105300725,...,MONO,01,9110,IMMEUBLE LE FLORIAN,IMMEUBLE LE FLORIAN,NaN,NaN,1.0,1.0,20161231.0

In [22]:
df_sirus18[df_sirus18['enseigne_et1'].notna()].iloc[0]

sirus_id                                                                   120020011
nic                                                                             2575
ape                                                                            8411Z
apet                                                                           8411Z
eff_3112_et                                                                        1
eff_etp_et                                                                         1
eff_et_effet_daaaammjj                                                   2.01712e+07
enseigne_et1                                      DELEGATION DEP DE L'ACTION SOCIALE
nom_comm_et                                                                      NaN
adr_et_loc_geo                                                             105300175
adr_et_compl                                                                     NaN
adr_et_voie_num                                                                   23
adr_et_voie_repet                                                                NaN
adr_et_voie_type                                                                 RUE
adr_et_voie_lib                                                           BOURGMAYER
adr_et_cedex                                                                    1005
adr_et_distsp                                                                 BP 188
sir_adr_et_com_lib                                             BOURG EN BRESSE CEDEX
adr_et_post                                                                     1000
adr_et_l1                                      DRH MINISTERES ECONOMIQUES FINANCIERS
adr_et_l2                                         DELEGATION DEP DE L'ACTION SOCIALE
adr_et_l3                                                                        NaN
adr_et_l4                                                          23 RUE BOURGMAYER
adr_et_l5                                                                     BP 188
adr_et_l6                                                01005 BOURG EN BRESSE CEDEX
adr_et_l7                                                                        NaN
nic_siege                                                                       1155
unite_type                                                                         1
region                                                                            11
adr_depcom                                                                     75112
region_impl                                                                       11
region_mult                                                                     MAJO
tr_eff_etp                                                                        42
cj                                                                              7120
denom                              DIRECTION DES RESSOURCES HUMAINES DES MINISTER...
denom_condense                                 DRH MINISTERES ECONOMIQUES FINANCIERS
sigle                                                                         SG/DRH
enseigne                                                                         NaN
eff_3112_uniteLegale                                                            1698
eff_etp_uniteLegale                                                             1648
eff_effet_daaaammjj_uniteLegale                                          2.01712e+07
Name: 27, dtype: object

In [23]:
df_sirus18[df_sirus18['sirus_id']==120020011]

,sirus_id,nic,ape,apet,eff_3112_et,eff_etp_et,eff_et_effet_daaaammjj,enseigne_et1,nom_comm_et,adr_et_loc_geo,...,region_mult,tr_eff_etp,cj,denom,denom_condense,sigle,enseigne,eff_3112_uniteLegale,eff_etp_uniteLegale,eff_effet_daaaammjj_uniteLegale
27,120020011,2575,8411Z,8411Z,1.0,1.0,20171231.0,DELEGATION DEP DE L'ACTION SOCIALE,NaN,105300175,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0

In [26]:
with fs.open(os.path.join(remote_data_dir,'Sirus/split/sirus18_75.csv')) as f:
    df_sirus18_75 = pd.read_csv(f, sep=";")
print('nb lines : {}'.format(len(df_sirus18_75)))
df_sirus18_75.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (11,29) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

nb lines : 811972

,sirus_id,nic,ape,apet,eff_3112_et,eff_etp_et,eff_et_effet_daaaammjj,enseigne_et1,nom_comm_et,adr_et_loc_geo,...,region_mult,tr_eff_etp,cj,denom,denom_condense,sigle,enseigne,eff_3112_uniteLegale,eff_etp_uniteLegale,eff_effet_daaaammjj_uniteLegale
0,5580501,46,5210A,5210A,NaN,NaN,NaN,NaN,NaN,7510800178,...,MONO,12,5720,SOCIETE DES GLACIERES ET FRIGORIFIQUES DE SAIN...,SOC GLACIERES FRIGO SAINT-NAZAIRE,SGN,NaN,25.0,23.0,20071231.0
1,5780580,30,6430Z,6430Z,NaN,NaN,NaN,NaN,NaN,7510800071,...,MULT,NN,5499,IMMOBILIERE LOUIS THIRIET,IMMOBILIERE LOUIS THIRIET,ILT,NaN,NaN,NaN,NaN
2,6080170,43,5811Z,6820B,NaN,NaN,NaN,NaN,NaN,7511400270,...,QASI,11,5560,COOP BREIZH,COOP BREIZH,NaN,NaN,23.0,17.0,20171231.0
3,15450711,120,6492Z,6492Z,NaN,NaN,NaN,NaN,NaN,7510700157,...,MULT,NN,5710,CIT AEROSPACE HOLDINGS (FRANCE) SAS,CIT AEROSPACE HOLDINGS (FRANCE) SAS,NaN,NaN,NaN,NaN,NaN
4,16960031,33,4619A,4619A,NaN,NaN,NaN,NaN,NaN,7511700402,...,MULT,NN,6220,P E N E L E C,P E N E L E C,PENELEC,NaN,NaN,NaN,NaN

In [27]:
df_sirus18_75[df_sirus18_75['sirus_id']==120020011]

,sirus_id,nic,ape,apet,eff_3112_et,eff_etp_et,eff_et_effet_daaaammjj,enseigne_et1,nom_comm_et,adr_et_loc_geo,...,region_mult,tr_eff_etp,cj,denom,denom_condense,sigle,enseigne,eff_3112_uniteLegale,eff_etp_uniteLegale,eff_effet_daaaammjj_uniteLegale
4933,120020011,173,8411Z,8411Z,NaN,NaN,NaN,SECRETAR COMM TITRE RESTAUR,NaN,7510800130,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4934,120020011,397,8411Z,8411Z,0.0,0.0,20161231.0,NaN,NaN,7510100221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4935,120020011,405,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510100206,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4936,120020011,439,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510100196,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4937,120020011,447,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510100145,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4938,120020011,454,8411Z,8411Z,3.0,5.0,20171231.0,ANNEXE ODL,NaN,7511200215,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4939,120020011,462,8411Z,8411Z,190.0,187.0,20071231.0,NaN,NaN,7511300428,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4940,120020011,520,8411Z,8411Z,30.0,31.0,20171231.0,ANNEXE BAC,NaN,7510700245,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4941,120020011,538,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510100091,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4942,120020011,546,8411Z,8411Z,NaN,NaN,NaN,ANNEXE MALAKOFF,NaN,7511400057,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4943,120020011,553,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510900068,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4944,120020011,579,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510900076,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4945,120020011,587,8411Z,8411Z,NaN,NaN,NaN,ANNEXE TOUR DE LYON,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4946,120020011,603,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510900206,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4947,120020011,629,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7511700341,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4948,120020011,660,8411Z,8411Z,5.0,5.0,20061231.0,ANNEXE BEAUTREILLIS,NaN,7510400154,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4949,120020011,686,8411Z,8411Z,0.0,1.0,20171231.0,NaN,NaN,7511200468,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4950,120020011,694,8411Z,8411Z,NaN,NaN,NaN,NaN,NaN,7510100167,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4951,120020011,744,8411Z,8411Z,30.0,31.0,20171231.0,NaN,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4952,120020011,1155,8411Z,8411Z,770.0,747.0,20171231.0,NaN,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4953,120020011,1353,8411Z,8411Z,NaN,NaN,NaN,ANNEXE RIVOLI,NaN,7510100206,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4954,120020011,1361,8411Z,8411Z,NaN,NaN,NaN,ANNEXE DES PONDS VERTS,NaN,7511200331,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4955,120020011,1379,8411Z,8411Z,NaN,NaN,NaN,ANNEXE DIDEROT,NaN,7511200294,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4956,120020011,1478,8411Z,8411Z,33.0,33.0,20171231.0,ANNEXE CHAMPS ELYSEES,NaN,7510800084,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4957,120020011,1528,8411Z,8411Z,NaN,NaN,NaN,ANNEXE LOUISE WEISS,NaN,7511300286,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4958,120020011,1536,8411Z,8411Z,NaN,NaN,NaN,ANNEXE RICHELIEU,NaN,7510100204,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4959,120020011,1981,8411Z,8411Z,1.0,1.0,20171231.0,SOUS-DIR ACTION SOCIALE - ATRIUM 151,NaN,7511200530,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4960,120020011,2146,8411Z,8411Z,NaN,NaN,NaN,MEDIATEUR SCE UNIVERSEL POSTAL MEDIASUP,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4961,120020011,2153,8411Z,8411Z,0.0,0.0,20161231.0,6EME SOUS-DIRECTION : LOGISTIQUE,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4962,120020011,2161,8411Z,8411Z,0.0,1.0,20111231.0,7EME SOUS-DIRECTION : IMMOBILIER,NaN,7511200530,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4963,120020011,2179,8411Z,8411Z,NaN,NaN,NaN,5EME SOUS-DIRECTION : BUDGET FINANCEMENT,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4964,120020011,2187,8411Z,8411Z,240.0,235.0,20061231.0,4EME SOUS-DIRECTION : PERSONNEL,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4965,120020011,2195,8411Z,8411Z,NaN,NaN,NaN,1ERE SOUS-DIRECT MODERNISATION PROSPECT,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4966,120020011,2203,8411Z,8411Z,1.0,1.0,20091231.0,2EME SOUS-DIRECTION RELATIONS SOCIALES,NaN,7511200221,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0
4967,120020011,2518,8411Z,8411Z,123.0,117.0,20171231.0,DELEGATION DEP ACTION SOCIALE,NaN,7511200530,...,MAJO,42,7120,DIRECTION DES RESSOURCES HUMAINES DES MINISTER...,DRH MINISTERES ECONOMIQUES FINANCIERS,SG/DRH,NaN,1698.0,1648.0,20171231.0

In [28]:
df_sirus18_75.iloc[4952]

sirus_id                                                                   120020011
nic                                                                             1155
ape                                                                            8411Z
apet                                                                           8411Z
eff_3112_et                                                                      770
eff_etp_et                                                                       747
eff_et_effet_daaaammjj                                                   2.01712e+07
enseigne_et1                                                                     NaN
nom_comm_et                                                                      NaN
adr_et_loc_geo                                                            7511200221
adr_et_compl                                                                     NaN
adr_et_voie_num                                                                  139
adr_et_voie_repet                                                                NaN
adr_et_voie_type                                                                 RUE
adr_et_voie_lib                                                             DE BERCY
adr_et_cedex                                                                   75572
adr_et_distsp                                                                    NaN
sir_adr_et_com_lib                                                    PARIS CEDEX 12
adr_et_post                                                                    75012
adr_et_l1                                      DRH MINISTERES ECONOMIQUES FINANCIERS
adr_et_l2                                                                        NaN
adr_et_l3                                                                        NaN
adr_et_l4                                                           139 RUE DE BERCY
adr_et_l5                                                                   PARIS 12
adr_et_l6                                                       75572 PARIS CEDEX 12
adr_et_l7                                                                        NaN
nic_siege                                                                       1155
unite_type                                                                         1
region                                                                            11
adr_depcom                                                                     75112
region_impl                                                                       11
region_mult                                                                     MAJO
tr_eff_etp                                                                        42
cj                                                                              7120
denom                              DIRECTION DES RESSOURCES HUMAINES DES MINISTER...
denom_condense                                 DRH MINISTERES ECONOMIQUES FINANCIERS
sigle                                                                         SG/DRH
enseigne                                                                         NaN
eff_3112_uniteLegale                                                            1698
eff_etp_uniteLegale                                                             1648
eff_effet_daaaammjj_uniteLegale                                          2.01712e+07
Name: 4952, dtype: object

In [58]:
df_sirus18_75[df_sirus18_75['eff_etp_uniteLegale'].isna()]

,sirus_id,nic,ape,apet,eff_3112_et,eff_etp_et,eff_et_effet_daaaammjj,enseigne_et1,nom_comm_et,adr_et_loc_geo,...,region_mult,tr_eff_etp,cj,denom,denom_condense,sigle,enseigne,eff_3112_uniteLegale,eff_etp_uniteLegale,eff_effet_daaaammjj_uniteLegale
1,5780580,30,6430Z,6430Z,NaN,NaN,NaN,NaN,NaN,7510800071,...,MULT,NN,5499,IMMOBILIERE LOUIS THIRIET,IMMOBILIERE LOUIS THIRIET,ILT,NaN,NaN,NaN,NaN
3,15450711,120,6492Z,6492Z,NaN,NaN,NaN,NaN,NaN,7510700157,...,MULT,NN,5710,CIT AEROSPACE HOLDINGS (FRANCE) SAS,CIT AEROSPACE HOLDINGS (FRANCE) SAS,NaN,NaN,NaN,NaN,NaN
4,16960031,33,4619A,4619A,NaN,NaN,NaN,NaN,NaN,7511700402,...,MULT,NN,6220,P E N E L E C,P E N E L E C,PENELEC,NaN,NaN,NaN,NaN
821,38931291,17,8110Z,8110Z,NaN,NaN,NaN,NaN,NaN,7510800191,...,MONO,NN,9110,SCI DU RUISSEAU DES GAINS,SCI DU RUISSEAU DES GAINS,NaN,NaN,NaN,NaN,NaN
3853,39292271,10,8110Z,8110Z,NaN,NaN,NaN,NaN,NaN,7511400294,...,MONO,NN,9110,SYND COPR DU 12 18 RUE MONTBRUN 75014 PA,SYND COPR DU 12 18 RUE MONTBRUN 75014,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811936,956512958,52,5229A,5229A,NaN,NaN,NaN,NaN,NaN,7511200203,...,MULT,NN,5599,TRANSPORTS VALLIER ET VICHER FRERES,TRANSPORTS VALLIER ET VICHER FRERES,NaN,NaN,NaN,NaN,NaN
811941,957809858,21,6820A,6820A,NaN,NaN,NaN,NaN,NaN,7510200161,...,MULT,NN,5499,CONSTRUCT MODERNES COTE D AZUR,CONSTRUCT MODERNES COTE D AZUR,SCMCA,NaN,NaN,NaN,NaN
811944,962501698,55,6920Z,6920Z,NaN,NaN,NaN,NaN,NaN,7511800295,...,MULT,NN,5499,SORECO SOCIETE DE REVISION COMPTABLE,SORECO SOCIETE DE REVISION COMPTABLE,NaN,NaN,NaN,NaN,NaN
811960,997838008,40,8559A,8559A,NaN,NaN,NaN,NaN,NaN,7510800275,...,MULT,NN,5599,POLYFORMATIQUE,POLYFORMATIQUE,NaN,NaN,NaN,NaN,NaN
811961,997838008,57,8559A,8559A,NaN,NaN,NaN,NaN,NaN,7510800144,...,MULT,NN,5599,POLYFORMATIQUE,POLYFORMATIQUE,NaN,NaN,NaN,NaN,NaN

In [50]:
set(df_sirus18_75['region_mult'].values)

{'MAJO', 'MONO', 'MULT', 'QASI'}